spring:
  datasource:
    #url: jdbc:sqlserver://axitybot.database.windows.net:1433;database=chatbot;user=adminxity@axitybot;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    #username: adminxity
    #password: Project123.
    url: jdbc:postgresql://10.11.1.235:5433/postgres
    username: postgres
    password: project123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: beca-service
  profiles:
    active: dev

server:
  port: 9090

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://gatewayservice:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5   
    preferIpAddress: true
